format = """
[](#50FA7B)\
$username$hostname\
[](bg:#6272A4 fg:#50FA7B)\
$directory\
[](fg:#6272A4 bg:#FFB86C)\
$git_branch\
$git_status\
[](fg:#FFB86C bg:#8BE9FD)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#8BE9FD bg:#8BE9FD)\
$docker_context\
[](fg:#8BE9FD bg:#6272A4)\
$time\
[ ](fg:#6272A4)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#50FA7B fg:#44475A"
style_root = "bg:#50FA7B fg:#44475A"
format = '[$user]($style)'

# You can also replace your username with a neat symbol like  to save some space
[hostname]
style = "bg:#50FA7B fg:#44475A"
ssh_only = false
format = '[@$hostname ]($style)'

[directory]
style = "bg:#6272A4 fg:#F8F8F2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A fg:#44475A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#8BE9FD fg:#44475A"
 format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FFB86C fg:#44475A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FFB86C fg:#44475A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#8BE9FD fg:#44475A"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6272A4 fg:#F8F8F2"
format = '[ ♥ $time ]($style)'
